title:              Sanatd
email:              iletisim.analogrock@gmail.com
description:        Sanata Dair Her şey!
author:             Burak Güner
baseurl:            ""
url:                "https://ornekblog.tk"

# Social Profiles
twitter_username:   analog_rock
github_username:    
facebook_username:  rockanalog
instagram_username: analog.rock
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
